// <auto-generated />
using System;
using ManagementPanelProject.DAL.ContextInfo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManagementPanelProject.DAL.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.LoginActivityModel", b =>
                {
                    b.Property<Guid>("LoginActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LogInDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LoginIsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LoginStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogoutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginActivityID");

                    b.HasIndex("UserName");

                    b.ToTable("LoginActivty");
                });

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.RoleModel", b =>
                {
                    b.Property<string>("RoleName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleName");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.UserModel", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.UserRoleModel", b =>
                {
                    b.Property<string>("UserRoleUserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserRoleRoleName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserRoleUserName", "UserRoleRoleName");

                    b.HasIndex("UserRoleRoleName");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.LoginActivityModel", b =>
                {
                    b.HasOne("ManagementPanelProject.Entity.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserName");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ManagementPanelProject.Entity.Models.UserRoleModel", b =>
                {
                    b.HasOne("ManagementPanelProject.Entity.Models.RoleModel", "Role")
                        .WithMany()
                        .HasForeignKey("UserRoleRoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManagementPanelProject.Entity.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserRoleUserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
